### ISSUE TITLE
Create a Maven repository for our mods

### ISSUE THREAD

**Issue by jellysquid3** [CaffeineMC/caffeine-meta#3]
We currently do not provide a Maven repository with artifacts for our mods. This has been asked many times by developers wishing to integrate with Lithium and Sodium. Right now, the go-to solution for most people is to depend on Modrinth's Maven repository (which involves no effort on our part) or to use Jitpack (involves a lot of trouble, often breaks.)

I'm able to allocate (from our existing credit balance on UpCloud, made possible by people using our referral code) up to $10/mo in credits for this server, which allows the following configurations:

- 1 CORE, 1 GB RAM, 25 GB SSD + 80 GB HDD, 1 TB transfer/month
- 1 CORE, 2 GB RAM, 50 GB SSD, 2 TB transfer/month

Some questions to ask here:
- What software exists for running a Maven repository? We care about it being minimally involved and lightweight, as we don't have endless resources to pour into a server.
- Should we put the repository behind Cloudflare? This seems like an obvious "yes" for reducing our bandwidth requirements and improving global performance, but I do not know if caching will cause problems.
- Do we publish snapshot artifacts on every commit? Personally, I think these would create a lot of noise and greatly increase our bandwidth requirements. Keeping it to release artifacts only keeps our repository small and reduces load for us. 
- How do we publish to this Maven repository from GitHub? I assume there's a workflow for this.

**Comment by yitzy299** [comment]
> What software exists for running a Maven repository? We care about it being minimally involved and lightweight, as we don't have endless resources to pour into a server.

[Reposilite](https://reposilite.com/) is great - it requires minimal configuration to get started and seriously lightweight - it suggests 128mb of RAM for a medium to high traffic repo.

> Do we publish snapshot artifacts on every commit? Personally, I think these would create a lot of noise and greatly increase our bandwidth requirements. Keeping it to release artifacts only keeps our repository small and reduces load for us.

There likely isn't a need for this - but what would be useful is publishing mod testing builds to the repo. It would make life easier for devs porting their mods, which rely on these mods, to new MC versions. Every commit seems excessive

>How do we publish to this Maven repository from GitHub? I assume there's a workflow for this.

[Plasmid's release workflow](https://github.com/NucleoidMC/plasmid/blob/1.16/.github/workflows/build.yml) does this, it would be simple to set up

**Comment by jellysquid3** [comment]
> Reposilite is great - it requires minimal configuration to get started and seriously lightweight - it suggests 128mb of RAM for a medium to high traffic repo.

This looks like a great option. Good mention! We could set this up pretty easily.

> There likely isn't a need for this - but what would be useful is publishing mod testing builds to the repo. It would make life easier for devs porting their mods, which rely on these mods, to new MC versions. Every commit seems excessive

I think tagging alpha/beta builds in VCS and publishing those on Maven is fine. This would be minimal work for us. I don't see the appeal of snapshot builds, and I don't really think they have a place outside of local repositories, really.

**Comment by jellysquid3** [comment]
Answering my own question here:

> Should we put the repository behind Cloudflare?

This should be perfectly fine. Objects stored in a Maven repository are immutable (excluding snapshot releases), and if we cared about it, we could create a simple Cloudflare rule to not cache those for more than a few minutes. But I'd rather just not allow snapshot/mutable Maven publications.

**Comment by MeeniMc** [comment]
Using gh-pages to host the maven could also be an option **https://github.com/andy-berry-dev/gh-pages-maven-repo**

**Comment by OroArmor** [comment]
1. github doesnt like people using pages for code hosting.
2. that implementation of an upload is very questionable and would be much better in a task than how its done there

**Comment by jellysquid3** [comment]
I think the questions about how we host a Maven repository is solved at this point, but I have some additional thoughts/questions about backups, archival, and uptime.

**Uptime.** I think the biggest thing to cover here is that we should _not_ tie the Maven repository to any specific machine. We should be containerizing our Maven server deployment, so that if we lose the server it's running on, we can clone it to a new machine with minimal downtime. This is a pretty easy problem to solve, and we're already doing it for our website and bots.

To add to this point, the storage volume for the Maven repository should not be tied to any specific machine. On UpCloud, we can simply use their attached volumes product for this, which gives us a redundant disk array in their datacenter that can be moved between servers quite easily. Since we don't expect very heavy I/O, the performance impact of this is not really meaningful (most of it should be cached either in memory or on a CDN.)

**Backups and archival.** UpCloud provides a service for backing up your server's directly attached disk (which would hold the operating system and container in this case), but doesn't offer backups for attached volumes. Solving this is a little bit more tricky, but I can offer my own resources on this and periodically back up the repository to my server at home, which also has a redundant mechanical disk array.

However, I think we can go a step further with our backup/archival strategy by allowing other people to mirror our repository with `rsync`. This is really quite simple, and essentially just involves running a SSH server within another container, and giving it read-only access to the repository's filesystem. Mirrors would just need to periodically run `rsync` to download any files that have changed since their last sync, and then serve these files behind any HTTP server.

Of course, we'd only want to give trusted parties mirror access to our repository, but I think the idea holds up. I'm curious to know what what the community's interest in this is, and if there's any possible security concerns with allowing it for that matter.

**Comment by jellysquid3** [comment]
I also want to say that I'm open to the idea of allowing other developers to host their own Maven artifacts on our server ex-gratia, provided fair use of our available storage and bandwidth. :slightly_smiling_face: With a mirroring system set up, I think it could become beneficial for the community at a slightly larger scale.

**Comment by jellysquid3** [comment]
Spent a few hours on this tonight. Everything looks good to me, but it's pretty empty for the time being. 
https://maven.caffeinemc.net

It's containerized and sitting behind an Argo Tunnel through Cloudflare. I've also set up caching rules so their edge should absorb pretty much all the traffic for release artifacts. All in all, very painless, and it should be easy to re-deploy quickly elsewhere if we lose our server (unlikely.)
